<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-F9CGR0U" failures="1" tests="1" name="Default test(failed)(failed)(failed)" time="7.175" errors="0" timestamp="2023-08-11T09:59:57 EDT">
  <testcase classname="com.selenium.aspiration.tests.AspirationTest" name="testGettingStarted" time="0.453">
    <failure type="java.lang.AssertionError" message="expected [https://my.aspiration.com/auth/login/existing-user] but found [https://www.aspiration.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://my.aspiration.com/auth/login/existing-user] but found [https://www.aspiration.com/]
at com.selenium.aspiration.tests.AspirationTest.testGettingStarted(AspirationTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGettingStarted -->
  <testcase classname="com.selenium.aspiration.tests.AspirationTest" name="testViewProducts" time="0.0">
    <ignored/>
  </testcase> <!-- testViewProducts -->
  <testcase classname="com.selenium.aspiration.tests.AspirationTest" name="testSignIn" time="0.0">
    <ignored/>
  </testcase> <!-- testSignIn -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
